name: '${project.name}'
version: '${project.version}'
main: net.pandadev.sharedbackpacks.Main
api-version: 1.13
authors: [ PandaDEV ]
description: '${project.description}'
website: https://pandadev.net
commands:
  backpacks:
    permission: sharedbackpacks.config.*
    aliases:
      - bps
  backpack:
    permission: sharedbackpacks.use
    aliases:
      - bag
      - b
      - bp